### ISSUE TITLE
PHP Notice – yii\base\ErrorException   Undefined variable: t

### ISSUE THREAD

**Issue by Mujazoji** [JakobReiter/Tabbie2#28]
While setting it up, i get this error at 
Tabbie2-master\tabbie2.git\frontend\views\site\index.php

**Comment by JakobReiter** [comment]
hmmm `Yii:t` is the translation module from yii - did you run `composer install`?
Can you tell me more about it? Like line, etc

**Comment by Mujazoji** [comment]
Yes i ran it. The line number is 26

**Comment by JakobReiter** [comment]
Sorry this must be wrong `frontend\views\site\index.php`has no function `t`
https://github.com/JakobReiter/Tabbie2/blob/master/tabbie2.git/frontend/views/site/index.php#L26
Can you post a full screenshot?

**Comment by Mujazoji** [comment]
![capture](https://cloud.githubusercontent.com/assets/21006553/17642839/4e97341e-616f-11e6-9237-4179e0b1f85f.PNG)

**Comment by JakobReiter** [comment]
Oh I see! Because the $t (a single tournament on the frontpage) is not defined ... this should have been blocked by line 23 but for whatever reason it passes there.
I assume there is something wrong with your database, since this should not happen according to the code.
Ideas to try:
- check your php version to support `<?=`
- check your database to have a proper tournament object
- add a `&& $t` to the condition on line 23

Let me know what it was. Also feel free to submit a merge request

**Comment by JakobReiter** [comment]
@Mujazoji - did you solve the issue?

**Comment by Mujazoji** [comment]
No it didnt. I tried all the things you advised me to. 
Q. What is the recommended php version ?
![image](https://cloud.githubusercontent.com/assets/21006553/19371081/af1afc0a-91c9-11e6-8a29-ca5dfb5c7cb5.png)

**Comment by wanaryytel** [comment]
@JakobReiter Any updates here?

**Comment by rscoates** [comment]
I've got a free hour. I'll take a look. Not something I've fiddled with.

**Comment by Mujazoji** [comment]
Anything?

**Comment by wanaryytel** [comment]
@Mujazoji Did you figure this one out?
